/**
* EatersLab API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package labs.pooh.client.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param name 
 * @param description 
 * @param subDescription 
 * @param longitude 
 * @param latitude 
 * @param capacity 
 * @param id 
 */

data class Cafeteria (
    @SerializedName("name")
    var name: kotlin.String,
    @SerializedName("description")
    var description: kotlin.String,
    @SerializedName("sub_description")
    var subDescription: kotlin.String,
    @SerializedName("longitude")
    var longitude: java.math.BigDecimal,
    @SerializedName("latitude")
    var latitude: java.math.BigDecimal,
    @SerializedName("capacity")
    var capacity: kotlin.Int,
    @SerializedName("id")
    var id: kotlin.Int? = null
) 



