# Generated by Django 3.0.5 on 2020-05-04 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('sub_description', models.CharField(max_length=512)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('logo_url', models.CharField(max_length=2048, validators=[django.core.validators.URLValidator])),
                ('address', models.CharField(max_length=256)),
                ('opened_from', models.TimeField()),
                ('opened_to', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FixedMenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('photo_url', models.CharField(max_length=2048, validators=[django.core.validators.URLValidator])),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_menu_options', to='api.Cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOptionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=32)),
                ('option', models.ManyToManyField(related_name='menu_option_tags', to='api.FixedMenuOption')),
            ],
        ),
        migrations.CreateModel(
            name='FixedMenuOptionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('author_nick', models.CharField(max_length=64)),
                ('review_time', models.DateTimeField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_menu_option_reviews', to='api.FixedMenuOption')),
            ],
        ),
    ]
