# Generated by Django 3.0.4 on 2020-05-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fixedmenuoption_avg_review_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.IntegerField(choices=[(0, 'monitoring_started'), (1, 'monitoring_ended'), (2, 'person_entered'), (3, 'person_left')])),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Camera')),
            ],
        ),
    ]
