# Generated by Django 3.0.6 on 2020-05-24 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_camera_cameraevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='state',
            field=models.IntegerField(choices=[(0, 'online'), (1, 'offline'), (2, 'lost_connection')], default=1),
            preserve_default=False,
        ),
    ]
