# Generated by Django 3.0.6 on 2020-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_camera_cameraevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='state',
            field=models.IntegerField(choices=[(0, 'online'), (1, 'offline'), (2, 'lost connection')], default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cameraevent',
            index=models.Index(fields=['camera_id', 'timestamp'], name='api_camerae_camera__cbd3b0_idx'),
        ),
    ]
