# Generated by Django 3.0.6 on 2020-05-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200524_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='last_update',
            new_name='last_event',
        ),
    ]
