# Generated by Django 3.0.6 on 2020-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cafeteria_owner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cameraevent',
            name='api_camerae_camera__cbd3b0_idx',
        ),
        migrations.RenameField(
            model_name='cameraevent',
            old_name='camera_id',
            new_name='camera',
        ),
        migrations.AddIndex(
            model_name='cameraevent',
            index=models.Index(fields=['camera', 'timestamp'], name='api_camerae_camera__922b87_idx'),
        ),
    ]
