# Generated by Django 3.0.6 on 2020-05-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200524_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='last_event',
        ),
        migrations.AddIndex(
            model_name='cameraevent',
            index=models.Index(fields=['camera_id', 'timestamp'], name='api_camerae_camera__cbd3b0_idx'),
        ),
    ]
