# Generated by Django 3.0.6 on 2020-05-27 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200526_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='occupancy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='cafeteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Cafeteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameraevent',
            name='cafeteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Cafeteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameraevent',
            name='event_value',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cameraevent',
            name='camera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Camera'),
        ),
        migrations.AlterField(
            model_name='cameraevent',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'monitoring_started'), (1, 'monitoring_ended'), (2, 'person_entered'), (3, 'person_left'), (4, 'occupancy_override')]),
        ),
    ]
