# Generated by Django 3.0.6 on 2020-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200527_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafeteria',
            options={'verbose_name': 'cafeteria', 'verbose_name_plural': 'cafeterias'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'camera', 'verbose_name_plural': 'cameras'},
        ),
        migrations.AlterModelOptions(
            name='cameraevent',
            options={'verbose_name': 'camera event', 'verbose_name_plural': 'camera events'},
        ),
        migrations.AlterModelOptions(
            name='fixedmenuoption',
            options={'verbose_name': 'fixed menu entry', 'verbose_name_plural': 'fixed menu entries'},
        ),
        migrations.AlterModelOptions(
            name='fixedmenuoptionreview',
            options={'verbose_name': 'menu entry review', 'verbose_name_plural': 'menu entry reviews'},
        ),
        migrations.RemoveField(
            model_name='camera',
            name='description',
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='description_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='description_pl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='name_pl',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='sub_description_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='sub_description_pl',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fixedmenuoption',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fixedmenuoption',
            name='name_pl',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fixedmenuoption',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MenuOptionTag',
        ),
    ]
