# Generated by Django 3.0.6 on 2020-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200527_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='description_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='description_pl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='name_pl',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='sub_description_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='sub_description_pl',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fixedmenuoption',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fixedmenuoption',
            name='name_pl',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
