# Generated by Django 3.0.6 on 2020-05-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200528_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedmenuoption',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MenuOptionTag',
        ),
    ]
