# Generated by Django 3.0.6 on 2020-05-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_translations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cameraevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('camera__isnull', True), ('event_type__in', [4])), models.Q(('camera__isnull', False), ('event_type__in', [0, 1, 2, 3])), _connector='OR'), name='camera_nullable_per_type'),
        ),
        migrations.AddConstraint(
            model_name='cameraevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event_type__in', [0, 1, 2, 3]), ('event_value__isnull', True)), models.Q(('event_type__in', [4]), ('event_value__isnull', False)), _connector='OR'), name='event_value_nullable_per_type'),
        ),
    ]
