# Generated by Django 3.0.4 on 2020-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_camera_event_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedmenuoptionreview',
            name='review_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
