# Generated by Django 3.0.7 on 2020-06-08 16:17

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200607_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cafeteria',
            field=models.ForeignKey(limit_choices_to=api.models.user_cafeterias_only, on_delete=django.db.models.deletion.CASCADE, to='api.Cafeteria'),
        ),
        migrations.AlterField(
            model_name='fixedmenuoption',
            name='cafeteria',
            field=models.ForeignKey(limit_choices_to=api.models.user_cafeterias_only, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_menu_options', to='api.Cafeteria'),
        ),
    ]
