# Generated by Django 3.0.7 on 2020-06-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200608_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafeteria',
            old_name='opened_from',
            new_name='open_from',
        ),
        migrations.RenameField(
            model_name='cafeteria',
            old_name='opened_to',
            new_name='open_to',
        ),
    ]
