# Generated by Django 3.0.7 on 2020-06-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200608_1622'),
        ('api', '0013_auto_20200608_1817'),
    ]

    operations = [
    ]
